routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);
Route::get('/', 'WarrantyController@index')->name('guest.home');
Route::get('/test', 'WarrantyController@indexTest')->name('guest.home.test');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('guest.check.warranty');
Route::post('post-login', 'Auth\LoginController@postLogin')->name('user.login.post'); 
Route::post('/logout/submit', 'Auth\LoginController@logout')->name('user.logout.submit');
Route::get('/terms-conditions', 'WarrantyController@termsConditions')->name('guest.terms');
Route::get('/product-usage-guide', 'WarrantyController@usageGuide')->name('guest.usage.guide');

// Reset password
Route::get('forget-password', 'Auth\ForgotPasswordController@showForgetPasswordForm')->name('forget.password.get');
Route::post('forget-password', 'Auth\ForgotPasswordController@submitForgetPasswordForm')->name('forget.password.post');
Route::get('reset-password/{token}', 'Auth\ForgotPasswordController@showResetPasswordForm')->name('reset.password.get');
Route::post('reset-password', 'Auth\ForgotPasswordController@submitResetPasswordForm')->name('reset.password.post');

Route::post('new-warranty','WarrantyController@store')->name('guest.new.warranty');
Route::post('upload-image-media','WarrantyController@storeMedia')->name('guest.new.store.media');
Route::post('remove-image-media','WarrantyController@deleteMedia')->name('guest.new.remove.media');
Route::post('upload-image',['as'=>'image.upload','uses'=>'WarrantyController@uploadImages']);
Route::post('image/{id}/edit/','WarrantyController@edit')->name('guest.remove.image'); 

Route::get('gshops', 'WarrantyController@autocomplete')->name('guest.autocomplete');
Route::get('checkemail', 'WarrantyController@checkemail')->name('guest.check.email');
Route::get('checkinvoice', 'WarrantyController@checkinvoice')->name('guest.check.invoice');
Route::get('cities/get_by_states', 'WarrantyController@get_by_states')->name('guest.cities.states');
Route::get('postcodes/get_by_cities', 'WarrantyController@get_by_cities')->name('guest.postcode.cities');
//Route::get('/image-upload', 'HomeController@upload')->name('test.upload');
//Rouxte::post('image-submit','HomeController@store')->name('test.upload.post');

Route::group(['prefix' => '/user', 'middleware'=>['auth']], function () {
    Route::get('/', 'HomeController@index')->name('user.home');
    Route::get('/home2', 'HomeController@home2')->name('user.home2');
    Route::get('/show/{id}', 'HomeController@show')->name('user.warranty.show');
    Route::get('/home2', 'HomeController@home2')->name('home2');
    Route::get('/terms-conditions', 'HomeController@termsConditions')->name('user.terms');
    Route::get('cities/get_by_states', 'HomeController@get_by_states')->name('user.cities.states');
    Route::get('postcodes/get_by_cities', 'HomeController@get_by_cities')->name('user.postcode.cities');
    
    //AJAX DropZone
    Route::post('/upload-image-media','UserWarrantyController@storeMedia')->name('user.store.media');
    Route::post('/remove-image-media','UserWarrantyController@deleteMedia')->name('user.remove.media');
    
    Route::get('/autocomplete', 'UserWarrantyController@autocomplete')->name('user.autocomplete');
    Route::get('/new-submission','UserWarrantyController@index')->name('user.new.warranty');
    Route::get('/re-submission/{id}','UserWarrantyController@update')->name('user.re.submission');
    Route::post('/new-warranty','UserWarrantyController@store')->name('user.new.warranty.store');
    Route::post('/upload-image',['as'=>'user.image.upload','uses'=>'UserWarrantyController@uploadImages']);
    Route::post('/re-upload-image',['as'=>'user.image.re.upload','uses'=>'UserWarrantyController@reuploadImages']);
    Route::post('/image/{id}/edit/','UserWarrantyController@edit')->name('user.remove.image');
    Route::post('/resubmit/','UserWarrantyController@updateResubmit')->name('user.resubmit.save');
    Route::get('/download-pdf/{id}','UserWarrantyController@downloadPDF')->name('user.warranty.pdf');
    Route::get('/download-pdf-powerflexx/{id}','UserWarrantyController@downloadPDFPowerflexx')->name('user.warranty.pdf.powerflexx');
    
    // Password Change
    Route::get('/change-password', 'HomeController@changePassword')->name('user.change.password.form');
    Route::post('/change-password', 'HomeController@changPasswordStore')->name('user.change.password');
    
});
/**
 * Admin routes
 */
Route::group(['prefix' => '/admin'], function () {
    // Login Routes
    //Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login'); 
    //Route::get('/elfinder', '\Barryvdh\Elfinder\ElfinderController@showIndex')->name('admin.elfinder.index'); 
    
    Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/login', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', [ 'as' => 'login', 'Backend\Auth\LoginController@showLoginForm']);
    Route::post('/login/submit', 'Backend\Auth\LoginController@login')->name('admin.login.submit');

    // Logout Routes
    Route::post('/logout/submit', 'Backend\Auth\LoginController@logout')->name('admin.logout.submit');

    // Forget Password Routes
    Route::get('/forget-password', 'Backend\Auth\ForgotPasswordController@getEmail')->name('admin.forgot_password');
    Route::post('/forget-password', 'Backend\Auth\ForgotPasswordController@postEmail')->name('admin.password.submit');
    
    Route::get('/reset-password/{token}', 'Backend\Auth\ResetPasswordController@getPassword')->name('admin.password.reset');
    Route::post('/reset-password-update', 'Backend\Auth\ResetPasswordController@updatePassword')->name('admin.password.update');
    
    Route::get('/shop/{token}','Backend\EmailShopsController@index')->name('guest.shop.token');
    Route::post('/shop-update', 'Backend\EmailShopsController@update')->name('guest.shop.update');
    //Route::group(['middleware' => ['auth']], function() { 
    Route::middleware('auth:admin')->group(function () {    
        //Auth::routes(); 
        Route::get('/dashboard', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::get('/manager', 'Backend\DashboardController@manager')->name('manager.dashboard');
        Route::get('/sale', 'Backend\DashboardController@sale')->name('sales.dashboard');
        //Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::resource('/settings/roles', 'Backend\RolesController', ['names' => 'admin.roles']);
        Route::get('/settings/roles/{id}/delete/', 'Backend\RolesController@destroy')->name('admin.roles.delete');
        
        Route::resource('users', 'Backend\UsersController', ['names' => 'admin.users']);
        Route::resource('/settings/admins', 'Backend\AdminsController', ['names' => 'admin.admins']);

        // Global Email Template
        Route::resource('/settings/global-email-templates','Backend\GlobalEmailTemplatesController');
        Route::get('/settings/global-email-templates/{id}/edit/','Backend\GlobalEmailTemplatesController@edit');
        Route::get('/settings/global-email-templates/{id}/delete/', 'Backend\GlobalEmailTemplatesController@destroy')->name('global-email-templates.delete');

        // Shops
        Route::resource('/shops','Backend\ShopsController');
        Route::get('/shops/{id}/edit/','Backend\ShopsController@edit');
        Route::get('/shops/{id}/delete/', 'Backend\ShopsController@destroy')->name('shops.delete');

        // Warranty
        Route::resource('/warranties/warranty','Backend\PurchaseController');
        Route::get('/warranties/edit-sales/{id}','Backend\PurchaseController@editsales')->name('warranty.edit.sales');
        Route::get('/warranties/accepted/','Backend\PurchaseController@accepted')->name('warranty.accepted');
        Route::get('/warranties/reviews/','Backend\PurchaseController@reviews')->name('warranty.reviews');
        Route::get('/warranties/approve/','Backend\PurchaseController@approve')->name('warranty.approve');
        Route::get('/warranties/decline/','Backend\PurchaseController@decline')->name('warranty.decline');
        Route::get('/warranties/pdf/{id}','Backend\PurchaseController@createPDF')->name('warranty.pdf');
        Route::get('/warranties/pdfpowerflexx/{id}','Backend\PurchaseController@createPDFPowerflexx')->name('warranty.pdf.powerflexx');
        Route::get('/warranties/send-shop-info/{id}','Backend\PurchaseController@sendEmail')->name('warranty.send.shop.info');
        
        Route::get('/warranties/edit-customer/{id}','Backend\PurchaseController@editCustomer')->name('warranty.edit.customer');
        Route::post('/warranties/edit-customer','Backend\PurchaseController@updateCustomer')->name('warranty.customer.save');
        
        Route::get('/warranties/on-behalf/','Backend\PurchaseController@onBehalf')->name('warranty.onbehalf');
        Route::get('/warranties/cities/', 'Backend\PurchaseController@get_by_states')->name('warranty.cities.states');
        Route::get('/warranties/postcode/', 'Backend\PurchaseController@get_by_cities')->name('warranty.postcode.cities');
        Route::get('/warranties/shops/', 'Backend\PurchaseController@get_by_shops')->name('warranty.sale.shops');
        
        Route::get('/warranties/{id}/edit/','Backend\PurchaseController@edit');
        Route::get('/warranties/{id}/delete/', 'Backend\PurchaseController@destroy')->name('warranty.delete');
        Route::get('/warranties/{id}/test/','Backend\PurchaseController@emailtest');
        

resources/views/admin/pages/admins/create.blade.php

@extends('admin.layouts.app')

@section('title')
Admin Create - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->
    <link href="{{ asset('themes/dashforge/lib/prismjs/themes/prism-vs.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('page-style')
    <!-- Start datatable css -->
    
@endsection

@section('content')

<!-- page title area start -->
<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-8"><h4 class="mg-b-0">Create Admin</h4></div>
  <div class="col-sm-4 text-right">
      
  </div>
</div>
<!-- page title area end -->


<form action="{{ route('admin.admins.store') }}" method="POST" data-parsley-validate>
    {{ csrf_field() }}
    <div class="form-row">
        <div class="form-group col-md-6 col-sm-12">
            <label for="name">Admin Name <span class="tx-danger">*</span></label>
            <input type="text" class="form-control" id="name" value="{{old('name')}}" name="name" placeholder="Enter Name" required>
            @if ($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
        </div>
        <div class="form-group col-md-6 col-sm-12">
            <label for="email">Admin Email <span class="tx-danger">*</span></label>
            <input type="text" class="form-control" id="email" value="{{old('email')}}" name="email" placeholder="Enter Email" required>
            @if ($errors->has('email'))
            <span class="text-danger">{{ $errors->first('email') }}</span>
            @endif
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6 col-sm-12">
            <label for="password">Password <span class="tx-danger">*</span></label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
            @if ($errors->has('password'))
            <span class="text-danger">{{ $errors->first('password') }}</span>
            @endif
        </div>
        <div class="form-group col-md-6 col-sm-12">
            <label for="password_confirmation">Confirm Password <span class="tx-danger">*</span></label>
            <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Enter Password" required>
            @if ($errors->has('password_confirmation'))
            <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
            @endif
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6 col-sm-6">
            <label for="password">Assign Roles <span class="tx-danger">*</span></label>
            <select name="roles[]" id="roles" class="form-control select2" multiple="multiple">
                @foreach ($roles as $role)
                <option value="{{ $role->name }}">{{ $role->name }}</option>
                @endforeach
            </select>
            @if ($errors->has('roles'))
            <span class="text-danger">{{ $errors->first('roles') }}</span>
            @endif
        </div>
    </div>

    
    <a href="{{route('admin.admins.index')}}" class="btn btn-warning mr-1"><i class="ft-x"></i> Cancel</a>

    <button type="submit" class="btn btn-primary">
        <i class="la la-check-square-o"></i> Save
    </button>
</form>

@endsection


@section('vendor-script')
<script src="{{ asset('themes/dashforge/lib/prismjs/prism.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/parsleyjs/parsley.min.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection


@section('page-script')
<script>
      // Adding placeholder for search input
      (function($) {

        'use strict'

        var Defaults = $.fn.select2.amd.require('select2/defaults');

        $.extend(Defaults.defaults, {
          searchInputPlaceholder: ''
        });

        var SearchDropdown = $.fn.select2.amd.require('select2/dropdown/search');

        var _renderSearchDropdown = SearchDropdown.prototype.render;

        SearchDropdown.prototype.render = function(decorated) {

          // invoke parent method
          var $rendered = _renderSearchDropdown.apply(this, Array.prototype.slice.apply(arguments));

          this.$search.attr('placeholder', this.options.get('searchInputPlaceholder'));

          return $rendered;
        };

      })(window.jQuery);


      $(function(){
        'use strict'

        // Basic with search
        $('.select2').select2({
          placeholder: 'Choose one',
          searchInputPlaceholder: 'Search options'
        });

        // Disable search
        $('.select2-no-search').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one'
        });

        // Clearable selection
        $('.select2-clear').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          allowClear: true
        });

        // Limit selection
        $('.select2-limit').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          maximumSelectionLength: 2
        });

      });
    </script>
@endsection

resources/views/admin/pages/admins/edit.blade.php

@extends('admin.layouts.app')

@section('title')
Admin Edit - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->
    <link href="{{ asset('themes/dashforge/lib/prismjs/themes/prism-vs.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('page-style')
    <!-- Start datatable css -->
    
@endsection

@section('content')

<!-- page title area start -->
<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-8"><h4 class="mg-b-0">Create Admin</h4></div>
  <div class="col-sm-4 text-right">
      
  </div>
</div>
<!-- page title area end -->


<form action="{{ route('admin.admins.update', $admin->id) }}" method="POST" data-parsley-validate>
    {{ csrf_field() }}
    <div class="form-row">
        <div class="form-group col-md-6 col-sm-12">
            <label for="name">Admin Name <span class="tx-danger">*</span></label>
            <input type="text" class="form-control" id="name" value="{{ $admin->name }}" name="name" placeholder="Enter Name" required>
            @if ($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
        </div>
        <div class="form-group col-md-6 col-sm-12">
            <label for="email">Admin Email <span class="tx-danger">*</span></label>
            <input type="text" class="form-control" id="email" value="{{ $admin->email }}" name="email" placeholder="Enter Email" required>
            @if ($errors->has('email'))
            <span class="text-danger">{{ $errors->first('email') }}</span>
            @endif
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6 col-sm-12">
            <label for="password">Password <span class="tx-danger">*</span></label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password" required>
            @if ($errors->has('password'))
            <span class="text-danger">{{ $errors->first('password') }}</span>
            @endif
        </div>
        <div class="form-group col-md-6 col-sm-12">
            <label for="password_confirmation">Confirm Password <span class="tx-danger">*</span></label>
            <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Enter Password" required>
            @if ($errors->has('password_confirmation'))
            <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
            @endif
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6 col-sm-6">
            <label for="password">Assign Roles <span class="tx-danger">*</span></label>
            <select name="roles[]" id="roles" class="form-control select2" multiple="multiple">
                @foreach ($roles as $role)
                    <option value="{{ $role->name }}" {{ $admin->hasRole($role->name) ? 'selected' : '' }}>{{ $role->name }}</option>
                @endforeach
            </select>
            @if ($errors->has('roles'))
            <span class="text-danger">{{ $errors->first('roles') }}</span>
            @endif
        </div>
    </div>

    
    <a href="{{route('admin.admins.index')}}" class="btn btn-warning mr-1"><i class="ft-x"></i> Cancel</a>

    <button type="submit" class="btn btn-primary">
        <i class="la la-check-square-o"></i> Save
    </button>
</form>

@endsection


@section('vendor-script')
<script src="{{ asset('themes/dashforge/lib/prismjs/prism.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/parsleyjs/parsley.min.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection


@section('page-script')
<script>
      // Adding placeholder for search input
      (function($) {

        'use strict'

        var Defaults = $.fn.select2.amd.require('select2/defaults');

        $.extend(Defaults.defaults, {
          searchInputPlaceholder: ''
        });

        var SearchDropdown = $.fn.select2.amd.require('select2/dropdown/search');

        var _renderSearchDropdown = SearchDropdown.prototype.render;

        SearchDropdown.prototype.render = function(decorated) {

          // invoke parent method
          var $rendered = _renderSearchDropdown.apply(this, Array.prototype.slice.apply(arguments));

          this.$search.attr('placeholder', this.options.get('searchInputPlaceholder'));

          return $rendered;
        };

      })(window.jQuery);


      $(function(){
        'use strict'

        // Basic with search
        $('.select2').select2({
          placeholder: 'Choose one',
          searchInputPlaceholder: 'Search options'
        });

        // Disable search
        $('.select2-no-search').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one'
        });

        // Clearable selection
        $('.select2-clear').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          allowClear: true
        });

        // Limit selection
        $('.select2-limit').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          maximumSelectionLength: 2
        });

      });
    </script>
@endsection

resources/views/admin/pages/admins/index.blade.php

@extends('admin.layouts.app')

@section('title')
Admins - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->
    
    <link href="{{ asset('themes/dashforge/lib/datatables.net-dt/css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('content')

<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-8"><h4 class="mg-b-0">Admins</h4></div>
  <div class="col-sm-4 text-right">
      @if (Auth::guard('admin')->user()->can('admin.edit'))
      <a class="btn btn-primary mr-1 mb-1 btn-sm" href="{{ route('admin.admins.create') }}">Create New</a>
      @endif
  </div>
</div>

<div class="df-example demo-table">
    <table id="example1" class="table">
        <thead>
            <tr>
                <th width="5%">Sl</th>
                <th width="10%">Name</th>
                <th width="10%">Email</th>
                <th width="40%">Roles</th>
                <th width="15%">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($admins as $admin)
            <tr>
                <td>{{ $loop->index+1 }}</td>
                <td>{{ $admin->name }}</td>
                <td>{{ $admin->email }}</td>
                <td>
                    @foreach ($admin->roles as $role)
                    <span class="badge badge-info mr-1">
                        {{ $role->name }}
                    </span>
                    @endforeach
                </td>
                
                <td>
                    @if (Auth::guard('admin')->user()->can('admin.edit'))
                    <a href="{{ route('admin.admins.edit', $admin->id) }}"><i class="far fa-edit"></i></a>
                    @endif

                    @if (Auth::guard('admin')->user()->can('admin.delete'))
                    <a href="{{route('admin.admins.destroy', $role->id)}}" data-toggle="tooltip" data-placement="bottom" title="Delete" onclick="return confirm('Are you sure to delete this item?')"><i class="fa fa-trash"></i></a>
                    
                    @endif
                </td>
                
                
            </tr>
            @endforeach
        </tbody>
    </table>
    
</div>



@endsection


@section('vendor-script')
     <!-- Start datatable js -->
    <script src="{{ asset('themes/dashforge/lib/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-dt/js/dataTables.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection

@section('page-script')
    <script>
      $(function(){
        'use strict'

        $('#example1').DataTable({
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          }
        });
        $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
      });
    </script>
@endsection