routes/web.php
Route::post('remove-image-media','WarrantyController@deleteMedia')->name('guest.new.remove.media');
Route::post('upload-image',['as'=>'image.upload','uses'=>'WarrantyController@uploadImages']);
Route::post('image/{id}/edit/','WarrantyController@edit')->name('guest.remove.image'); 

Route::get('gshops', 'WarrantyController@autocomplete')->name('guest.autocomplete');
Route::get('checkemail', 'WarrantyController@checkemail')->name('guest.check.email');
Route::get('checkinvoice', 'WarrantyController@checkinvoice')->name('guest.check.invoice');
Route::get('cities/get_by_states', 'WarrantyController@get_by_states')->name('guest.cities.states');
Route::get('postcodes/get_by_cities', 'WarrantyController@get_by_cities')->name('guest.postcode.cities');
//Route::get('/image-upload', 'HomeController@upload')->name('test.upload');
//Rouxte::post('image-submit','HomeController@store')->name('test.upload.post');

Route::group(['prefix' => '/user', 'middleware'=>['auth']], function () {
    Route::get('/', 'HomeController@index')->name('user.home');
    Route::get('/home2', 'HomeController@home2')->name('user.home2');
    Route::get('/show/{id}', 'HomeController@show')->name('user.warranty.show');
    Route::get('/home2', 'HomeController@home2')->name('home2');
    Route::get('/terms-conditions', 'HomeController@termsConditions')->name('user.terms');
    Route::get('cities/get_by_states', 'HomeController@get_by_states')->name('user.cities.states');
    Route::get('postcodes/get_by_cities', 'HomeController@get_by_cities')->name('user.postcode.cities');
    
    //AJAX DropZone
    Route::post('/upload-image-media','UserWarrantyController@storeMedia')->name('user.store.media');
    Route::post('/remove-image-media','UserWarrantyController@deleteMedia')->name('user.remove.media');
    
    Route::get('/autocomplete', 'UserWarrantyController@autocomplete')->name('user.autocomplete');
    Route::get('/new-submission','UserWarrantyController@index')->name('user.new.warranty');
    Route::get('/re-submission/{id}','UserWarrantyController@update')->name('user.re.submission');
    Route::post('/new-warranty','UserWarrantyController@store')->name('user.new.warranty.store');
    Route::post('/upload-image',['as'=>'user.image.upload','uses'=>'UserWarrantyController@uploadImages']);
    Route::post('/re-upload-image',['as'=>'user.image.re.upload','uses'=>'UserWarrantyController@reuploadImages']);
    Route::post('/image/{id}/edit/','UserWarrantyController@edit')->name('user.remove.image');
    Route::post('/resubmit/','UserWarrantyController@updateResubmit')->name('user.resubmit.save');
    Route::get('/download-pdf/{id}','UserWarrantyController@downloadPDF')->name('user.warranty.pdf');
    Route::get('/download-pdf-powerflexx/{id}','UserWarrantyController@downloadPDFPowerflexx')->name('user.warranty.pdf.powerflexx');
    
    // Password Change
    Route::get('/change-password', 'HomeController@changePassword')->name('user.change.password.form');
    Route::post('/change-password', 'HomeController@changPasswordStore')->name('user.change.password');
    
});
/**
 * Admin routes
 */
Route::group(['prefix' => '/admin'], function () {
    // Login Routes
    //Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login'); 
    //Route::get('/elfinder', '\Barryvdh\Elfinder\ElfinderController@showIndex')->name('admin.elfinder.index'); 
    
    Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/login', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', [ 'as' => 'login', 'Backend\Auth\LoginController@showLoginForm']);
    Route::post('/login/submit', 'Backend\Auth\LoginController@login')->name('admin.login.submit');

    // Logout Routes
    Route::post('/logout/submit', 'Backend\Auth\LoginController@logout')->name('admin.logout.submit');

    // Forget Password Routes
    Route::get('/forget-password', 'Backend\Auth\ForgotPasswordController@getEmail')->name('admin.forgot_password');
    Route::post('/forget-password', 'Backend\Auth\ForgotPasswordController@postEmail')->name('admin.password.submit');
    
    Route::get('/reset-password/{token}', 'Backend\Auth\ResetPasswordController@getPassword')->name('admin.password.reset');
    Route::post('/reset-password-update', 'Backend\Auth\ResetPasswordController@updatePassword')->name('admin.password.update');
    
    Route::get('/shop/{token}','Backend\EmailShopsController@index')->name('guest.shop.token');
    Route::post('/shop-update', 'Backend\EmailShopsController@update')->name('guest.shop.update');
    //Route::group(['middleware' => ['auth']], function() { 
    Route::middleware('auth:admin')->group(function () {    
        //Auth::routes(); 
        Route::get('/dashboard', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::get('/manager', 'Backend\DashboardController@manager')->name('manager.dashboard');
        Route::get('/sale', 'Backend\DashboardController@sale')->name('sales.dashboard');
        //Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::resource('/settings/roles', 'Backend\RolesController', ['names' => 'admin.roles']);
        Route::get('/settings/roles/{id}/delete/', 'Backend\RolesController@destroy')->name('admin.roles.delete');
        
        Route::resource('users', 'Backend\UsersController', ['names' => 'admin.users']);
        Route::resource('/settings/admins', 'Backend\AdminsController', ['names' => 'admin.admins']);

        // Global Email Template
        Route::resource('/settings/global-email-templates','Backend\GlobalEmailTemplatesController');
        Route::get('/settings/global-email-templates/{id}/edit/','Backend\GlobalEmailTemplatesController@edit');
        Route::get('/settings/global-email-templates/{id}/delete/', 'Backend\GlobalEmailTemplatesController@destroy')->name('global-email-templates.delete');

        // Shops
        Route::resource('/shops','Backend\ShopsController');
        Route::get('/shops/{id}/edit/','Backend\ShopsController@edit');
        Route::get('/shops/{id}/delete/', 'Backend\ShopsController@destroy')->name('shops.delete');

        // Warranty
        Route::resource('/warranties/warranty','Backend\PurchaseController');
        Route::get('/warranties/edit-sales/{id}','Backend\PurchaseController@editsales')->name('warranty.edit.sales');
        Route::get('/warranties/accepted/','Backend\PurchaseController@accepted')->name('warranty.accepted');
        Route::get('/warranties/reviews/','Backend\PurchaseController@reviews')->name('warranty.reviews');
        Route::get('/warranties/approve/','Backend\PurchaseController@approve')->name('warranty.approve');
        Route::get('/warranties/decline/','Backend\PurchaseController@decline')->name('warranty.decline');
        Route::get('/warranties/pdf/{id}','Backend\PurchaseController@createPDF')->name('warranty.pdf');
        Route::get('/warranties/pdfpowerflexx/{id}','Backend\PurchaseController@createPDFPowerflexx')->name('warranty.pdf.powerflexx');
        Route::get('/warranties/send-shop-info/{id}','Backend\PurchaseController@sendEmail')->name('warranty.send.shop.info');
        
        Route::get('/warranties/edit-customer/{id}','Backend\PurchaseController@editCustomer')->name('warranty.edit.customer');
        Route::post('/warranties/edit-customer','Backend\PurchaseController@updateCustomer')->name('warranty.customer.save');
        
        Route::get('/warranties/on-behalf/','Backend\PurchaseController@onBehalf')->name('warranty.onbehalf');
        Route::get('/warranties/cities/', 'Backend\PurchaseController@get_by_states')->name('warranty.cities.states');
        Route::get('/warranties/postcode/', 'Backend\PurchaseController@get_by_cities')->name('warranty.postcode.cities');
        Route::get('/warranties/shops/', 'Backend\PurchaseController@get_by_shops')->name('warranty.sale.shops');
        
        Route::get('/warranties/{id}/edit/','Backend\PurchaseController@edit');
        Route::get('/warranties/{id}/delete/', 'Backend\PurchaseController@destroy')->name('warranty.delete');
        Route::get('/warranties/{id}/test/','Backend\PurchaseController@emailtest');
        
        Route::get('/warranties/autocomplete', 'Backend\PurchaseController@autocomplete')->name('warranty.autocomplete');
        Route::post('/warranties/re-upload-image',['as'=>'warranty.image.re.upload','uses'=>'Backend\PurchaseController@reuploadImages']);
        Route::post('/warranties/upload-image-media','Backend\PurchaseController@storeMedia')->name('warranty.store.media');
        Route::post('/warranties/remove-image-media','Backend\PurchaseController@deleteMedia')->name('warranty.remove.media');
        Route::get('/warranties/checkemail', 'Backend\PurchaseController@checkemail')->name('warranty.check.email');
        
        
        Route::resource('/team','Backend\TeamPurchaseController');
        
        //Users
        Route::resource('/users','Backend\UsersController');
        
        // Sales PIC
        Route::resource('/sales','Backend\SalesManagerController');
        Route::get('/sales/{id}/edit/','Backend\SalesManagerController@edit');
        Route::get('/sales/{id}/delete/', 'Backend\SalesManagerController@destroy')->name('sales.delete');
        
        // Regional Manager
        Route::get('/managers/my-sales-team/','Backend\SalesManagerController@mysales')->name('my.sales.team');
        Route::resource('/managers','Backend\RegionalSalesManagerController');
        Route::get('/managers/{id}/edit/','Backend\RegionalSalesManagerController@edit');
        Route::get('/managers/{id}/delete/', 'Backend\RegionalSalesManagerController@destroy')->name('managers.delete');
        
        

        Route::get('/change-password', 'Backend\DashboardController@changePassword')->name('admin.change.password.form'); 

resources/views/admin/managers/create.blade.php
@extends('admin.layouts.app')

@section('title')
Create Regional Manager - Admin Panel
@endsection

@section('vendor-style')
    <link href="{{ asset('themes/dashforge/lib/prismjs/themes/prism-vs.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-12"><h4 class="mg-b-0">Create New Regional Manager</h4></div>
  
</div>
<form method="post" action="{{route('managers.store')}}" data-parsley-validate class="mg-t-20 mg-b-20">
    {{csrf_field()}}
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label required">Name</label>
        <div class="col-sm-10">
            <input type="text" value="{{old('name')}}" id="name" class="form-control" placeholder="Lim Hong" name="name" required>
            @if ($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label required">Email</label>
        <div class="col-sm-10">
            <input type="text" value="{{old('email')}}" id="email" class="form-control" placeholder="name@domain.com" name="email" required>
            @if ($errors->has('email'))
            <span class="text-danger">{{ $errors->first('email') }}</span>
            @endif
        </div>
    </div>
    
    <div class="form-group row">
        <label for="region" class="col-sm-2 col-form-label">Region</label>
        <div class="col-sm-10">
            <select class="custom-select" name="region" required>
                <option value="" selected>Select</option>
                <option value="Central">Central</option>
                <option value="East Coast">East Coast</option>
                <option value="Northern">Northern</option>
                <option value="Sabah">Sabah</option>
                <option value="Sarawak">Sarawak</option>
                <option value="Southern">Southern</option>
            </select>
            @if ($errors->has('region'))
            <span class="text-danger">{{ $errors->first('region') }}</span>
            @endif
        </div>
    </div>
    
    <div class="form-group row">
        <label for="assign-role" class="col-sm-2 col-form-label required">Assign Roles</label>
        <div class="col-sm-10">
            <select name="roles[]" id="roles" class="form-control select2" multiple="multiple">
                @foreach ($roles as $role)
                <option value="{{ $role->name }}">{{ $role->name }}</option>
                @endforeach
            </select>
            @if ($errors->has('roles'))
            <span class="text-danger">{{ $errors->first('roles') }}</span>
            @endif
        </div>
    </div>

    
    <div class="form-group row">
        <label for="status" class="col-sm-2 col-form-label required">Status</label>
        <div class="col-sm-10">
            <select class="custom-select" name="status" required>
                <option value="" selected>Select</option>
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
            </select>
            @if ($errors->has('status'))
            <span class="text-danger">{{ $errors->first('status') }}</span>
            @endif
        </div>
    </div>


    <div class="form-group row mg-b-0">
        <div class="col-sm-10 offset-2">
            <a href="{{route('managers.index')}}" class="btn btn-warning mr-1"><i class="ft-x"></i> Cancel</a>

            <button type="submit" class="btn btn-primary">
                <i class="la la-check-square-o"></i> Save
            </button>
        </div>
    </div>
</form>


@endsection

@section('vendor-script')
     <!-- Start datatable js -->
<script src="{{ asset('themes/dashforge/lib/prismjs/prism.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/parsleyjs/parsley.min.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection

@section('page-script')
<script>
      // Adding placeholder for search input
      (function($) {

        'use strict'

        var Defaults = $.fn.select2.amd.require('select2/defaults');

        $.extend(Defaults.defaults, {
          searchInputPlaceholder: ''
        });

        var SearchDropdown = $.fn.select2.amd.require('select2/dropdown/search');

        var _renderSearchDropdown = SearchDropdown.prototype.render;

        SearchDropdown.prototype.render = function(decorated) {

          // invoke parent method
          var $rendered = _renderSearchDropdown.apply(this, Array.prototype.slice.apply(arguments));

          this.$search.attr('placeholder', this.options.get('searchInputPlaceholder'));

          return $rendered;
        };

      })(window.jQuery);


      $(function(){
        'use strict'

        // Basic with search
        $('.select2').select2({
          placeholder: 'Choose one',
          searchInputPlaceholder: 'Search options'
        });

        // Disable search
        $('.select2-no-search').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one'
        });

        // Clearable selection
        $('.select2-clear').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          allowClear: true
        });

        // Limit selection
        $('.select2-limit').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          maximumSelectionLength: 2
        });

      });
    </script>    
@endsection

resources/views/admin/managers/edit.blade.php
@extends('admin.layouts.app')

@section('title')
Create Regional Manager - Admin Panel
@endsection

@section('vendor-style')
    <link href="{{ asset('themes/dashforge/lib/prismjs/themes/prism-vs.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-12"><h4 class="mg-b-0">Edit - {{$model->name}}</h4></div>
  
</div>
<form method="post" action="{{route('managers.update',$model->id)}}" data-parsley-validate class="mg-t-20 mg-b-20">
    {{ method_field('PUT') }}
    {{ csrf_field() }} 
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label required">Name</label>
        <div class="col-sm-10">
            <input type="text" value="{{$model->name}}" id="name" class="form-control" placeholder="Lim Hong" name="name" required>
            @if ($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label required">Email</label>
        <div class="col-sm-10">
            <input type="text" value="{{$model->email}}" id="email" class="form-control" placeholder="name@domain.com" name="email" required>
            @if ($errors->has('email'))
            <span class="text-danger">{{ $errors->first('email') }}</span>
            @endif
        </div>
    </div>
    
    <div class="form-group row">
        <label for="region" class="col-sm-2 col-form-label required">Region</label>
        <div class="col-sm-10">
            <select class="custom-select" name="region" required>
                <option value="" selected>Select</option>
                <option value="Central" {{ ($model->region=="Central")? "selected" : "" }}>Central</option>
                <option value="East Coast" {{ ($model->region=="East Coast")? "selected" : "" }}>East Coast</option>
                <option value="Northern" {{ ($model->region=="Northern")? "selected" : "" }}>Northern</option>
                <option value="Sabah" {{ ($model->region=="Sabah")? "selected" : "" }}>Sabah</option>
                <option value="Sarawak" {{ ($model->region=="Sarawak")? "selected" : "" }}>Sarawak</option>
                <option value="Southern" {{ ($model->region=="Southern")? "selected" : "" }}>Southern</option>
            </select>
            @if ($errors->has('region'))
            <span class="text-danger">{{ $errors->first('region') }}</span>
            @endif
        </div>
    </div>
    
    <div class="form-group row">
        <label for="assign-role" class="col-sm-2 col-form-label required">Assign Roles</label>
        <div class="col-sm-10">
            <select name="roles[]" id="roles" class="form-control select2" multiple="multiple">
                @foreach ($roles as $role)
                <option value="{{ $role->name }}" {{ $model->hasRole($role->name) ? 'selected' : '' }}>{{ $role->name }}</option>
                @endforeach
            </select>
            @if ($errors->has('roles'))
            <span class="text-danger">{{ $errors->first('roles') }}</span>
            @endif
        </div>
    </div>
    
    <div class="form-group row">
        <label for="status" class="col-sm-2 col-form-label required">Status</label>
        <div class="col-sm-10">
            <select class="custom-select" name="status" required>
                <option value="" selected>Select</option>
                <option value="active" {{ ($model->status=="active")? "selected" : "" }}>Active</option>
                <option value="inactive" {{ ($model->status=="inactive")? "selected" : "" }}>Inactive</option>
            </select>
            @if ($errors->has('status'))
            <span class="text-danger">{{ $errors->first('status') }}</span>
            @endif
        </div>
    </div>

    <div class="form-group row mg-b-0">
        <div class="col-sm-10 offset-2">
            <a href="{{route('managers.index')}}" class="btn btn-warning mr-1"><i class="ft-x"></i> Cancel</a>

            <button type="submit" class="btn btn-primary">
                <i class="la la-check-square-o"></i> Save
            </button>
        </div>
    </div>
</form>

@endsection

@section('vendor-script')
     <!-- Start datatable js -->
<script src="{{ asset('themes/dashforge/lib/prismjs/prism.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/parsleyjs/parsley.min.js') }}"></script>
 <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection

@section('page-script')
    <script>
      // Adding placeholder for search input
      (function($) {

        'use strict'

        var Defaults = $.fn.select2.amd.require('select2/defaults');

        $.extend(Defaults.defaults, {
          searchInputPlaceholder: ''
        });

        var SearchDropdown = $.fn.select2.amd.require('select2/dropdown/search');

        var _renderSearchDropdown = SearchDropdown.prototype.render;

        SearchDropdown.prototype.render = function(decorated) {

          // invoke parent method
          var $rendered = _renderSearchDropdown.apply(this, Array.prototype.slice.apply(arguments));

          this.$search.attr('placeholder', this.options.get('searchInputPlaceholder'));

          return $rendered;
        };

      })(window.jQuery);


      $(function(){
        'use strict'

        // Basic with search
        $('.select2').select2({
          placeholder: 'Choose one',
          searchInputPlaceholder: 'Search options'
        });

        // Disable search
        $('.select2-no-search').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one'
        });

        // Clearable selection
        $('.select2-clear').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          allowClear: true
        });

        // Limit selection
        $('.select2-limit').select2({
          minimumResultsForSearch: Infinity,
          placeholder: 'Choose one',
          maximumSelectionLength: 2
        });

      });
    </script>
@endsection

resources/views/admin/managers/index.blade.php
@extends('admin.layouts.app')

@section('title')
Regional Sales Manager - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->
    
    <link href="{{ asset('themes/dashforge/lib/datatables.net-dt/css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('content')


<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-8"><h4 class="mg-b-0">All Regional Manager</h4></div>
  <div class="col-sm-4 text-right">
      <a class="btn btn-primary mr-1 mb-1 btn-sm" href="{{ route('managers.create') }}">Create New</a>
  </div>
</div>

<div class="df-example demo-table">
    <table id="example1" class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Region</th>
                <th>Last Login</th>
                <th>Status</th>
                <th class="text-center">View</th>
            </tr>
        </thead>
        <tbody>
            @if(count($models) > 0)
            @foreach ($models as $model)                                
            <tr id="category_id_{{ $model->id }}">
                <td>{{ $loop->index+1 }}</td>
                <td>{{ $model->name }}</td>
                <td>{{ $model->email }}</td>
                <td>{{ $model->region }}</td>
                <td>
                    @if(!empty($model->date_last_login))
                    {{ $model->date_last_login->format('d-m-Y') }}
                    @else
                    N/A
                    @endif
                    
                </td>
                <td>{{ ucwords($model->status) }}</td>
                <td class="text-center">
                <!--<a href="" id="view" data-toggle="tooltip" data-placement="bottom" title="View"><i class="far fa-eye"></i></a>-->
                <a href="{{route('managers.edit',$model->id)}}" id="edit" data-toggle="tooltip" data-placement="bottom" title="Edit"><i class="far fa-edit"></i></a>
                </td>
            </tr>
            @endforeach
            @else
            <tr><td class="text-center" colspan="6">No records found!!!</td></tr>
            @endif
        </tbody>
    </table>
    
</div>

@endsection

@section('vendor-script')
     <!-- Start datatable js -->
    <script src="{{ asset('themes/dashforge/lib/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-dt/js/dataTables.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection

@section('page-script')
    <script>
      $(function(){
        'use strict'

        $('#example1').DataTable({
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          }
        });
        $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
      });
    </script>
@endsection