routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);
Route::get('/', 'WarrantyController@index')->name('guest.home');
Route::get('/test', 'WarrantyController@indexTest')->name('guest.home.test');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('guest.check.warranty');
Route::post('post-login', 'Auth\LoginController@postLogin')->name('user.login.post'); 
Route::post('/logout/submit', 'Auth\LoginController@logout')->name('user.logout.submit');
Route::get('/terms-conditions', 'WarrantyController@termsConditions')->name('guest.terms');
Route::get('/product-usage-guide', 'WarrantyController@usageGuide')->name('guest.usage.guide');

// Reset password
Route::get('forget-password', 'Auth\ForgotPasswordController@showForgetPasswordForm')->name('forget.password.get');
Route::post('forget-password', 'Auth\ForgotPasswordController@submitForgetPasswordForm')->name('forget.password.post');
Route::get('reset-password/{token}', 'Auth\ForgotPasswordController@showResetPasswordForm')->name('reset.password.get');
Route::post('reset-password', 'Auth\ForgotPasswordController@submitResetPasswordForm')->name('reset.password.post');

Route::post('new-warranty','WarrantyController@store')->name('guest.new.warranty');
Route::post('upload-image-media','WarrantyController@storeMedia')->name('guest.new.store.media');
Route::post('remove-image-media','WarrantyController@deleteMedia')->name('guest.new.remove.media');
Route::post('upload-image',['as'=>'image.upload','uses'=>'WarrantyController@uploadImages']);
Route::post('image/{id}/edit/','WarrantyController@edit')->name('guest.remove.image'); 

Route::get('gshops', 'WarrantyController@autocomplete')->name('guest.autocomplete');
Route::get('checkemail', 'WarrantyController@checkemail')->name('guest.check.email');
Route::get('checkinvoice', 'WarrantyController@checkinvoice')->name('guest.check.invoice');
Route::get('cities/get_by_states', 'WarrantyController@get_by_states')->name('guest.cities.states');
Route::get('postcodes/get_by_cities', 'WarrantyController@get_by_cities')->name('guest.postcode.cities');
//Route::get('/image-upload', 'HomeController@upload')->name('test.upload');
//Rouxte::post('image-submit','HomeController@store')->name('test.upload.post');

Route::group(['prefix' => '/user', 'middleware'=>['auth']], function () {
    Route::get('/', 'HomeController@index')->name('user.home');
    Route::get('/home2', 'HomeController@home2')->name('user.home2');
    Route::get('/show/{id}', 'HomeController@show')->name('user.warranty.show');
    Route::get('/home2', 'HomeController@home2')->name('home2');
    Route::get('/terms-conditions', 'HomeController@termsConditions')->name('user.terms');
    Route::get('cities/get_by_states', 'HomeController@get_by_states')->name('user.cities.states');
    Route::get('postcodes/get_by_cities', 'HomeController@get_by_cities')->name('user.postcode.cities');
    
    //AJAX DropZone
    Route::post('/upload-image-media','UserWarrantyController@storeMedia')->name('user.store.media');
    Route::post('/remove-image-media','UserWarrantyController@deleteMedia')->name('user.remove.media');
    
    Route::get('/autocomplete', 'UserWarrantyController@autocomplete')->name('user.autocomplete');
    Route::get('/new-submission','UserWarrantyController@index')->name('user.new.warranty');
    Route::get('/re-submission/{id}','UserWarrantyController@update')->name('user.re.submission');
    Route::post('/new-warranty','UserWarrantyController@store')->name('user.new.warranty.store');
    Route::post('/upload-image',['as'=>'user.image.upload','uses'=>'UserWarrantyController@uploadImages']);
    Route::post('/re-upload-image',['as'=>'user.image.re.upload','uses'=>'UserWarrantyController@reuploadImages']);
    Route::post('/image/{id}/edit/','UserWarrantyController@edit')->name('user.remove.image');
    Route::post('/resubmit/','UserWarrantyController@updateResubmit')->name('user.resubmit.save');
    Route::get('/download-pdf/{id}','UserWarrantyController@downloadPDF')->name('user.warranty.pdf');
    Route::get('/download-pdf-powerflexx/{id}','UserWarrantyController@downloadPDFPowerflexx')->name('user.warranty.pdf.powerflexx');
    
    // Password Change
    Route::get('/change-password', 'HomeController@changePassword')->name('user.change.password.form');
    Route::post('/change-password', 'HomeController@changPasswordStore')->name('user.change.password');
    
});
/**
 * Admin routes
 */
Route::group(['prefix' => '/admin'], function () {
    // Login Routes
    //Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login'); 
    //Route::get('/elfinder', '\Barryvdh\Elfinder\ElfinderController@showIndex')->name('admin.elfinder.index'); 
    
    Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/login', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', [ 'as' => 'login', 'Backend\Auth\LoginController@showLoginForm']);
    Route::post('/login/submit', 'Backend\Auth\LoginController@login')->name('admin.login.submit');

    // Logout Routes
    Route::post('/logout/submit', 'Backend\Auth\LoginController@logout')->name('admin.logout.submit');

    // Forget Password Routes
    Route::get('/forget-password', 'Backend\Auth\ForgotPasswordController@getEmail')->name('admin.forgot_password');
    Route::post('/forget-password', 'Backend\Auth\ForgotPasswordController@postEmail')->name('admin.password.submit');
    
    Route::get('/reset-password/{token}', 'Backend\Auth\ResetPasswordController@getPassword')->name('admin.password.reset');
    Route::post('/reset-password-update', 'Backend\Auth\ResetPasswordController@updatePassword')->name('admin.password.update');
    
    Route::get('/shop/{token}','Backend\EmailShopsController@index')->name('guest.shop.token');
    Route::post('/shop-update', 'Backend\EmailShopsController@update')->name('guest.shop.update');
    //Route::group(['middleware' => ['auth']], function() { 
    Route::middleware('auth:admin')->group(function () {    
        //Auth::routes(); 
        Route::get('/dashboard', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::get('/manager', 'Backend\DashboardController@manager')->name('manager.dashboard');
        Route::get('/sale', 'Backend\DashboardController@sale')->name('sales.dashboard');
        //Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::resource('/settings/roles', 'Backend\RolesController', ['names' => 'admin.roles']);
        Route::get('/settings/roles/{id}/delete/', 'Backend\RolesController@destroy')->name('admin.roles.delete');
        
        Route::resource('users', 'Backend\UsersController', ['names' => 'admin.users']);
        Route::resource('/settings/admins', 'Backend\AdminsController', ['names' => 'admin.admins']);

        // Global Email Template
        Route::resource('/settings/global-email-templates','Backend\GlobalEmailTemplatesController');
        Route::get('/settings/global-email-templates/{id}/edit/','Backend\GlobalEmailTemplatesController@edit');
        Route::get('/settings/global-email-templates/{id}/delete/', 'Backend\GlobalEmailTemplatesController@destroy')->name('global-email-templates.delete');

        // Shops
        Route::resource('/shops','Backend\ShopsController');
        Route::get('/shops/{id}/edit/','Backend\ShopsController@edit');
        Route::get('/shops/{id}/delete/', 'Backend\ShopsController@destroy')->name('shops.delete');

        // Warranty
        Route::resource('/warranties/warranty','Backend\PurchaseController');
        Route::get('/warranties/edit-sales/{id}','Backend\PurchaseController@editsales')->name('warranty.edit.sales');
        Route::get('/warranties/accepted/','Backend\PurchaseController@accepted')->name('warranty.accepted');
        Route::get('/warranties/reviews/','Backend\PurchaseController@reviews')->name('warranty.reviews');
        Route::get('/warranties/approve/','Backend\PurchaseController@approve')->name('warranty.approve');
        Route::get('/warranties/decline/','Backend\PurchaseController@decline')->name('warranty.decline');
        Route::get('/warranties/pdf/{id}','Backend\PurchaseController@createPDF')->name('warranty.pdf');
        Route::get('/warranties/pdfpowerflexx/{id}','Backend\PurchaseController@createPDFPowerflexx')->name('warranty.pdf.powerflexx');
        Route::get('/warranties/send-shop-info/{id}','Backend\PurchaseController@sendEmail')->name('warranty.send.shop.info');
        
        Route::get('/warranties/edit-customer/{id}','Backend\PurchaseController@editCustomer')->name('warranty.edit.customer');
        Route::post('/warranties/edit-customer','Backend\PurchaseController@updateCustomer')->name('warranty.customer.save');
        
        Route::get('/warranties/on-behalf/','Backend\PurchaseController@onBehalf')->name('warranty.onbehalf');
        Route::get('/warranties/cities/', 'Backend\PurchaseController@get_by_states')->name('warranty.cities.states');
        Route::get('/warranties/postcode/', 'Backend\PurchaseController@get_by_cities')->name('warranty.postcode.cities');
        Route::get('/warranties/shops/', 'Backend\PurchaseController@get_by_shops')->name('warranty.sale.shops');
        
        Route::get('/warranties/{id}/edit/','Backend\PurchaseController@edit');
        Route::get('/warranties/{id}/delete/', 'Backend\PurchaseController@destroy')->name('warranty.delete');
        Route::get('/warranties/{id}/test/','Backend\PurchaseController@emailtest');
        

resources/views/admin/layouts/panels/breadcrumb.blade.php
@if(@isset($breadcrumbs))
<ol class="breadcrumb df-breadcrumbs mg-b-10">
    @foreach ($breadcrumbs as $breadcrumb)
    <li class="breadcrumb-item">
        @if(isset($breadcrumb['link']))
        <a href="{{ $breadcrumb['link'] == 'javascript:void(0)' ? $breadcrumb['link']:url($breadcrumb['link']) }}">
            @endif
            {{$breadcrumb['name']}}
            @if(isset($breadcrumb['link']))
        </a>
        @endif
    </li>
    @endforeach
</ol>
@endisset

resources/views/admin/layouts/panels/footer.blade.php
<footer class="content-footer">
    <div>
        <span>&copy; <?php echo date('Y') ?> AkzoNobel </span>
    </div>
</footer><!-- content-footer -->

resources/views/admin/layouts/panels/header.blade.php
<header class="navbar navbar-header navbar-header-fixed">
      <a href="" id="sidebarMenuOpen" class="burger-menu"><i data-feather="arrow-left"></i></a>
      <div class="navbar-brand">
        <a href="/" class="df-logo">Akzo<span>Nobel</span></a>
      </div><!-- navbar-brand -->
      <div id="navbarMenu" class="navbar-menu-wrapper">
        <div class="navbar-menu-header">
          <a href="/" class="df-logo">Akzo<span>Nobel</span></a>
          <a id="mainMenuClose" href=""><i data-feather="x"></i></a>
        </div><!-- navbar-menu-header -->
      </div><!-- nav-wrapper -->
      <div class="navbar-right">
        <div class="dropdown dropdown-profile">
            <a href="" class="dropdown-link" data-toggle="dropdown" data-display="static">
                <div class="avatar avatar-sm"><img src="{{ Helper::admin_avatar() }}" class="rounded-circle" alt=""></div>
            </a><!-- dropdown-link -->
            <div class="dropdown-menu dropdown-menu-right tx-13">
                
                <h6 class="tx-semibold mg-b-5">{{ Auth::guard('admin')->user()->name }}</h6>
                <p class="mg-b-25 tx-12 tx-color-03">{{ Auth::guard('admin')->user()->email }}</p>

                <!--<a href="" class="dropdown-item"><i data-feather="edit-3"></i> Edit Profile</a>-->
                <a href="{{ route('admin.change.password.form') }}" class="dropdown-item"><i data-feather="lock"></i> Change Password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="javascript:void" onclick="$('#logout-form').submit();"><i data-feather="log-out"></i> Logout</a>
                <form id="logout-form" action="{{ route('admin.logout.submit') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </div><!-- dropdown-menu -->
        </div><!-- dropdown -->
      </div><!-- az-header-right -->
    </header><!-- navbar -->

resources/views/admin/layouts/panels/headerGuest.blade.php
<header class="navbar navbar-header navbar-header-fixed">
      <a href="" id="sidebarMenuOpen" class="burger-menu"><i data-feather="arrow-left"></i></a>
      <div class="navbar-brand">
        <a href="/" class="df-logo">Akzo<span>Nobel</span></a>
      </div><!-- navbar-brand -->
      <div id="navbarMenu" class="navbar-menu-wrapper">
        <div class="navbar-menu-header">
          <a href="/" class="df-logo">Akzo<span>Nobel</span></a>
          <a id="mainMenuClose" href=""><i data-feather="x"></i></a>
        </div><!-- navbar-menu-header -->
      </div><!-- nav-wrapper -->
    </header><!-- navbar -->

resources/views/admin/layouts/panels/messages.blade.php
@if ($message = Session::get('success'))
<script>
    toastr['success']('{{ $message }}', 'Success!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif


@if ($message = Session::get('error'))
<script>
      toastr['error']('{{ $message }}', 'Error!', {
      closeButton: true,
      tapToDismiss: false,
    });
    </script>
@endif


@if ($message = Session::get('warning'))
<script>
    toastr['warning']('{{ $message }}', 'Warning!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif


@if ($message = Session::get('info'))
<script>
    toastr['info']('{{ $message }}', 'Info!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif


@if ($errors->any())
<script>
    toastr['warning']('Please check the form below for errors', 'Warning!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif

resources/views/admin/layouts/panels/scripts.blade.php
{{-- Admin Vendor Scripts --}}
<script src="{{ asset('themes/dashforge/lib/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('themes/dashforge/lib/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('themes/dashforge/lib/feather-icons/feather.min.js') }}"></script>
<script src="{{ asset('themes/dashforge/lib/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>

@yield('vendor-script')
<script type="text/javascript" src="{{ asset('themes/dashforge/lib/toastr/extensions/toastr.min.js') }}"></script>

{{-- Theme Scripts --}}
<script src="{{ asset('themes/dashforge/assets/js/dashforge.js') }}"></script>
<script src="{{ asset('themes/dashforge/lib/toastr/toastr.js') }}"></script>

{{-- page script --}}
 @include('panels/messages')
@yield('page-script')
{{-- page script --}}

resources/views/admin/layouts/panels/sidebar.blade.php
@php
     $usr = Auth::guard('admin')->user();
 @endphp
<div id="sidebarMenu" class="sidebar sidebar-fixed sidebar-components">
      <div class="sidebar-header">
        <a href="" id="mainMenuOpen"><i data-feather="menu"></i></a>
        <h5>Akzo Nobel</h5>
        <a href="" id="sidebarMenuClose"><i data-feather="x"></i></a>
      </div><!-- sidebar-header -->
      <div class="sidebar-body">
        <ul class="sidebar-nav">

         <li class="nav-item"><a href="/" class="nav-link "><i data-feather="monitor"></i> Dashboard</a></li>
          @if ($usr->can('warranty.view') || $usr->can('warranty.accepted') ||  $usr->can('warranty.reviews') ||  $usr->can('warranty.approve') ||  $usr->can('warranty.decline'))
          <li class="nav-item {{ (request()->is('admin/warranties*')) ? 'show' : '' }}">
            <a href="" class="nav-link with-sub {{ (request()->is('admin/warranties*')) ? 'active' : '' }}"><i data-feather="layers"></i> Submissions</a>
            <nav class="nav">
              @if ($usr->can('warranty.on.behalf'))  
              <a href="{{ route('warranty.onbehalf') }}" class="{{ (request()->is('admin/warranties/on-behalf*')) ? 'active' : '' }}">New Submission</a>
              @endif  
              @if ($usr->can('warranty.view'))  
              <a href="{{ route('warranty.index') }}" class="{{ (request()->is('admin/warranties/warranty*')) ? 'active' : '' }}">All</a>
              @endif
              @if ($usr->can('warranty.accepted'))
              <a href="{{ route('warranty.accepted') }}" class="{{ (request()->is('admin/warranties/accepted*')) ? 'active' : '' }}">In Progress</a>
              @endif
              @if ($usr->can('warranty.reviews'))
              <a href="{{ route('warranty.reviews') }}" class="{{ (request()->is('admin/warranties/reviews*')) ? 'active' : '' }}">Reviews</a>
              @endif
              @if ($usr->can('warranty.approve'))
              <a href="{{ route('warranty.approve') }}" class="{{ (request()->is('admin/warranties/approve*')) ? 'active' : '' }}">Approved</a>
              @endif
              @if ($usr->can('warranty.decline'))
              <a href="{{ route('warranty.decline') }}" class="{{ (request()->is('admin/warranties/decline*')) ? 'active' : '' }}">Declined</a>
              @endif
            </nav>
          </li>
          @endif
          
          @if ($usr->can('managers.my.sales.team'))
          <li class="nav-item"><a href="{{ route('my.sales.team') }}" class="nav-link {{ (request()->is('admin/managers/my-sales-team')) ? 'active' : '' }}"><i data-feather="users"></i> My Sales Team</a></li>
          @endif
          @if ($usr->can('user.view'))
          <li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link {{ (request()->is('admin/users*')) ? 'active' : '' }}"><i data-feather="users"></i> Users</a></li>
          @endif
          
          @if ($usr->can('managers.view'))
          <li class="nav-item"><a href="{{ route('managers.index') }}" class="nav-link {{ (request()->is('admin/managers*')) ? 'active' : '' }}"><i data-feather="users"></i> Regional Manager</a></li>
          @endif
          @if ($usr->can('user.view'))
          <li class="nav-item"><a href="{{ route('sales.index') }}" class="nav-link {{ (request()->is('admin/sales*')) ? 'active' : '' }}"><i data-feather="users"></i> Sales PIC</a></li>
          @endif
          @if ($usr->can('shop.view'))
            <li class="nav-item"><a href="{{ route('shops.index') }}" class="nav-link {{ (request()->is('admin/shops*')) ? 'active' : '' }}"><i data-feather="briefcase"></i> Shops</a></li>
          @endif
          
          @if ($usr->can('email.view') || $usr->can('role.view') ||  $usr->can('admin.view')) 
          <li class="nav-item {{ (request()->is('admin/settings*')) ? 'show' : '' }}">
            <a href="" class="nav-link with-sub {{ (request()->is('admin/settings*')) ? 'active' : '' }}"><i data-feather="settings"></i> Settings</a>
            <nav class="nav">
              
              @if ($usr->can('email.view'))  
              <a href="{{ route('global-email-templates.index') }}" class="{{ (request()->is('admin/settings/global-email-templates*')) ? 'active' : '' }}">Email Templates</a>
              @endif
              
              @if ($usr->can('role.create') || $usr->can('role.view') ||  $usr->can('role.edit') ||  $usr->can('role.delete'))
              <a href="{{ route('admin.roles.index') }}" class="{{ (request()->is('admin/settings/roles*')) ? 'active' : '' }}">Roles</a>
              @endif
              
              @if ($usr->can('admin.create') || $usr->can('admin.view') ||  $usr->can('admin.edit') ||  $usr->can('admin.delete'))
              <a href="{{ route('admin.admins.index') }}" class="{{ (request()->is('admin/settings/admins*')) ? 'active' : '' }}">Admins</a>
              @endif
            </nav>
          </li>
          @endif
          
          <li class="nav-item"><a href="{{ route('admin.change.password.form') }}" class="nav-link "><i data-feather="lock"></i> Change Password</a></li>
          <li class="nav-item"><a href="javascript:void" onclick="$('#logout-form').submit();" class="nav-link "><i data-feather="log-out"></i> Logout</a></li>
                <form id="logout-form" action="{{ route('admin.logout.submit') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
        </ul>
      </div><!-- sidebar-body -->
    </div><!-- sidebar -->

resources/views/admin/layouts/panels/sidebar_manager.blade.php
@php
     $usr = Auth::guard('admin')->user();
 @endphp
<div id="sidebarMenu" class="sidebar sidebar-fixed sidebar-components">
      <div class="sidebar-header">
        <a href="" id="mainMenuOpen"><i data-feather="menu"></i></a>
        <h5>Akzo Nobel</h5>
        <a href="" id="sidebarMenuClose"><i data-feather="x"></i></a>
      </div><!-- sidebar-header -->
      <div class="sidebar-body">
        <ul class="sidebar-nav">

          <li class="nav-item"><a href="/" class="nav-link "><i data-feather="monitor"></i> Dashboard</a></li>
          
          @if ($usr->can('warranty.view') || $usr->can('warranty.accepted') ||  $usr->can('warranty.reviews') ||  $usr->can('warranty.approve') ||  $usr->can('warranty.decline'))
          <li class="nav-item {{ (request()->is('admin/warranties*')) ? 'show' : '' }}">
            <a href="" class="nav-link with-sub {{ (request()->is('admin/warranties*')) ? 'active' : '' }}"><i data-feather="layers"></i> Submissions</a>
            <nav class="nav">
              @if ($usr->can('warranty.view'))  
              <a href="{{ route('warranty.index') }}" class="{{ (request()->is('admin/warranties/warranty*')) ? 'active' : '' }}">All</a>
              @endif
              @if ($usr->can('warranty.accepted'))
              <a href="{{ route('warranty.accepted') }}" class="{{ (request()->is('admin/warranties/accepted*')) ? 'active' : '' }}">In Progress</a>
              @endif
              @if ($usr->can('warranty.reviews'))
              <a href="{{ route('warranty.reviews') }}" class="{{ (request()->is('admin/warranties/reviews*')) ? 'active' : '' }}">Reviews</a>
              @endif
              @if ($usr->can('warranty.approve'))
              <a href="{{ route('warranty.approve') }}" class="{{ (request()->is('admin/warranties/approve*')) ? 'active' : '' }}">Approved</a>
              @endif
              @if ($usr->can('warranty.decline'))
              <a href="{{ route('warranty.decline') }}" class="{{ (request()->is('admin/warranties/decline*')) ? 'active' : '' }}">Decline</a>
              @endif
            </nav>
          </li>
          @endif
          <li class="nav-item"><a href="{{ route('sales.index') }}" class="nav-link {{ (request()->is('admin/sales*')) ? 'active' : '' }}"><i data-feather="users"></i> My Sales PIC</a></li>
          <li class="nav-item"><a href="{{ route('shops.index') }}" class="nav-link {{ (request()->is('admin/shops*')) ? 'active' : '' }}"><i data-feather="briefcase"></i> My Shops</a></li>
        </ul>
      </div><!-- sidebar-body -->
    </div><!-- sidebar -->

resources/views/admin/layouts/panels/sidebar_sale.blade.php
@php
     $usr = Auth::guard('admin')->user();
 @endphp
<div id="sidebarMenu" class="sidebar sidebar-fixed sidebar-components">
      <div class="sidebar-header">
        <a href="" id="mainMenuOpen"><i data-feather="menu"></i></a>
        <h5>Akzo Nobel</h5>
        <a href="" id="sidebarMenuClose"><i data-feather="x"></i></a>
      </div><!-- sidebar-header -->
      <div class="sidebar-body">
        <ul class="sidebar-nav">

          <li class="nav-item"><a href="/" class="nav-link "><i data-feather="monitor"></i> Dashboard</a></li>
          
          @if ($usr->can('warranties.view') || $usr->can('warranties.accepted') ||  $usr->can('warranties.reviews') ||  $usr->can('warranties.approve') ||  $usr->can('warranties.warranties.decline'))
          <li class="nav-item {{ (request()->is('admin/warranties*')) ? 'show' : '' }}">
            <a href="" class="nav-link with-sub {{ (request()->is('admin/warranties*')) ? 'active' : '' }}"><i data-feather="layers"></i> Submissions</a>
            <nav class="nav">
              @if ($usr->can('warranties.view'))  
              <a href="{{ route('warranty.index') }}" class="{{ (request()->is('admin/warranties/warranty*')) ? 'active' : '' }}">All</a>
              @endif
              @if ($usr->can('warranties.accepted'))
              <a href="{{ route('warranty.accepted') }}" class="{{ (request()->is('admin/warranties/accepted*')) ? 'active' : '' }}">Accepted</a>
              @endif
              @if ($usr->can('warranties.reviews'))
              <a href="{{ route('warranty.reviews') }}" class="{{ (request()->is('admin/warranties/reviews*')) ? 'active' : '' }}">Reviews</a>
              @endif
              @if ($usr->can('warranties.approve'))
              <a href="{{ route('warranty.approve') }}" class="{{ (request()->is('admin/warranties/approve*')) ? 'active' : '' }}">Approved</a>
              @endif
              @if ($usr->can('warranties.decline'))
              <a href="{{ route('warranty.decline') }}" class="{{ (request()->is('admin/warranties/decline*')) ? 'active' : '' }}">Decline</a>
              @endif
            </nav>
          </li>
          @endif

          <li class="nav-item"><a href="{{ route('shops.index') }}" class="nav-link {{ (request()->is('admin/shops*')) ? 'active' : '' }}"><i data-feather="briefcase"></i> My Shops</a></li>
        </ul>
      </div><!-- sidebar-body -->
    </div><!-- sidebar -->

resources/views/admin/layouts/panels/styles.blade.php
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link href="{{ asset('themes/dashforge/lib/@fortawesome/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
<link href="{{ asset('themes/dashforge/lib/ionicons/css/ionicons.min.css') }}" rel="stylesheet">
<link href="{{ asset('themes/dashforge/lib/typicons.font/typicons.css') }}" rel="stylesheet">
<link href="{{ asset('themes/dashforge/lib/toastr/extensions/toastr.css') }}" rel="stylesheet" type="text/css">
<!-- END: Vendor CSS-->

{{-- Page Vendor --}}
@yield('vendor-style')

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" href="{{ asset('themes/dashforge/assets/css/dashforge.css') }}">
<link rel="stylesheet" href="{{ asset('themes/dashforge/assets/css/dashforge.demo.css') }}">
<link rel="stylesheet" href="{{ asset('themes/dashforge/lib/toastr/toastr.css') }}">
<link rel="stylesheet" href="{{ asset('themes/dashforge/assets/css/customadmin.css') }}">
<!-- END: Theme CSS-->

{{-- Page Styles --}}
@yield('page-style')