routes/web.php
Route::post('remove-image-media','WarrantyController@deleteMedia')->name('guest.new.remove.media');
Route::post('upload-image',['as'=>'image.upload','uses'=>'WarrantyController@uploadImages']);
Route::post('image/{id}/edit/','WarrantyController@edit')->name('guest.remove.image'); 

Route::get('gshops', 'WarrantyController@autocomplete')->name('guest.autocomplete');
Route::get('checkemail', 'WarrantyController@checkemail')->name('guest.check.email');
Route::get('checkinvoice', 'WarrantyController@checkinvoice')->name('guest.check.invoice');
Route::get('cities/get_by_states', 'WarrantyController@get_by_states')->name('guest.cities.states');
Route::get('postcodes/get_by_cities', 'WarrantyController@get_by_cities')->name('guest.postcode.cities');
//Route::get('/image-upload', 'HomeController@upload')->name('test.upload');
//Rouxte::post('image-submit','HomeController@store')->name('test.upload.post');

Route::group(['prefix' => '/user', 'middleware'=>['auth']], function () {
    Route::get('/', 'HomeController@index')->name('user.home');
    Route::get('/home2', 'HomeController@home2')->name('user.home2');
    Route::get('/show/{id}', 'HomeController@show')->name('user.warranty.show');
    Route::get('/home2', 'HomeController@home2')->name('home2');
    Route::get('/terms-conditions', 'HomeController@termsConditions')->name('user.terms');
    Route::get('cities/get_by_states', 'HomeController@get_by_states')->name('user.cities.states');
    Route::get('postcodes/get_by_cities', 'HomeController@get_by_cities')->name('user.postcode.cities');
    
    //AJAX DropZone
    Route::post('/upload-image-media','UserWarrantyController@storeMedia')->name('user.store.media');
    Route::post('/remove-image-media','UserWarrantyController@deleteMedia')->name('user.remove.media');
    
    Route::get('/autocomplete', 'UserWarrantyController@autocomplete')->name('user.autocomplete');
    Route::get('/new-submission','UserWarrantyController@index')->name('user.new.warranty');
    Route::get('/re-submission/{id}','UserWarrantyController@update')->name('user.re.submission');
    Route::post('/new-warranty','UserWarrantyController@store')->name('user.new.warranty.store');
    Route::post('/upload-image',['as'=>'user.image.upload','uses'=>'UserWarrantyController@uploadImages']);
    Route::post('/re-upload-image',['as'=>'user.image.re.upload','uses'=>'UserWarrantyController@reuploadImages']);
    Route::post('/image/{id}/edit/','UserWarrantyController@edit')->name('user.remove.image');
    Route::post('/resubmit/','UserWarrantyController@updateResubmit')->name('user.resubmit.save');
    Route::get('/download-pdf/{id}','UserWarrantyController@downloadPDF')->name('user.warranty.pdf');
    Route::get('/download-pdf-powerflexx/{id}','UserWarrantyController@downloadPDFPowerflexx')->name('user.warranty.pdf.powerflexx');
    
    // Password Change
    Route::get('/change-password', 'HomeController@changePassword')->name('user.change.password.form');
    Route::post('/change-password', 'HomeController@changPasswordStore')->name('user.change.password');
    
});
/**
 * Admin routes
 */
Route::group(['prefix' => '/admin'], function () {
    // Login Routes
    //Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login'); 
    //Route::get('/elfinder', '\Barryvdh\Elfinder\ElfinderController@showIndex')->name('admin.elfinder.index'); 
    
    Route::get('/', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/login', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', [ 'as' => 'login', 'Backend\Auth\LoginController@showLoginForm']);
    Route::post('/login/submit', 'Backend\Auth\LoginController@login')->name('admin.login.submit');

    // Logout Routes
    Route::post('/logout/submit', 'Backend\Auth\LoginController@logout')->name('admin.logout.submit');

    // Forget Password Routes
    Route::get('/forget-password', 'Backend\Auth\ForgotPasswordController@getEmail')->name('admin.forgot_password');
    Route::post('/forget-password', 'Backend\Auth\ForgotPasswordController@postEmail')->name('admin.password.submit');
    
    Route::get('/reset-password/{token}', 'Backend\Auth\ResetPasswordController@getPassword')->name('admin.password.reset');
    Route::post('/reset-password-update', 'Backend\Auth\ResetPasswordController@updatePassword')->name('admin.password.update');
    
    Route::get('/shop/{token}','Backend\EmailShopsController@index')->name('guest.shop.token');
    Route::post('/shop-update', 'Backend\EmailShopsController@update')->name('guest.shop.update');
    //Route::group(['middleware' => ['auth']], function() { 
    Route::middleware('auth:admin')->group(function () {    
        //Auth::routes(); 
        Route::get('/dashboard', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::get('/manager', 'Backend\DashboardController@manager')->name('manager.dashboard');
        Route::get('/sale', 'Backend\DashboardController@sale')->name('sales.dashboard');
        //Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
        Route::resource('/settings/roles', 'Backend\RolesController', ['names' => 'admin.roles']);
        Route::get('/settings/roles/{id}/delete/', 'Backend\RolesController@destroy')->name('admin.roles.delete');
        
        Route::resource('users', 'Backend\UsersController', ['names' => 'admin.users']);
        Route::resource('/settings/admins', 'Backend\AdminsController', ['names' => 'admin.admins']);

        // Global Email Template
        Route::resource('/settings/global-email-templates','Backend\GlobalEmailTemplatesController');
        Route::get('/settings/global-email-templates/{id}/edit/','Backend\GlobalEmailTemplatesController@edit');
        Route::get('/settings/global-email-templates/{id}/delete/', 'Backend\GlobalEmailTemplatesController@destroy')->name('global-email-templates.delete');

        // Shops
        Route::resource('/shops','Backend\ShopsController');
        Route::get('/shops/{id}/edit/','Backend\ShopsController@edit');
        Route::get('/shops/{id}/delete/', 'Backend\ShopsController@destroy')->name('shops.delete');

        // Warranty
        Route::resource('/warranties/warranty','Backend\PurchaseController');
        Route::get('/warranties/edit-sales/{id}','Backend\PurchaseController@editsales')->name('warranty.edit.sales');
        Route::get('/warranties/accepted/','Backend\PurchaseController@accepted')->name('warranty.accepted');
        Route::get('/warranties/reviews/','Backend\PurchaseController@reviews')->name('warranty.reviews');
        Route::get('/warranties/approve/','Backend\PurchaseController@approve')->name('warranty.approve');
        Route::get('/warranties/decline/','Backend\PurchaseController@decline')->name('warranty.decline');
        Route::get('/warranties/pdf/{id}','Backend\PurchaseController@createPDF')->name('warranty.pdf');
        Route::get('/warranties/pdfpowerflexx/{id}','Backend\PurchaseController@createPDFPowerflexx')->name('warranty.pdf.powerflexx');
        Route::get('/warranties/send-shop-info/{id}','Backend\PurchaseController@sendEmail')->name('warranty.send.shop.info');
        
        Route::get('/warranties/edit-customer/{id}','Backend\PurchaseController@editCustomer')->name('warranty.edit.customer');
        Route::post('/warranties/edit-customer','Backend\PurchaseController@updateCustomer')->name('warranty.customer.save');
        
        Route::get('/warranties/on-behalf/','Backend\PurchaseController@onBehalf')->name('warranty.onbehalf');
        Route::get('/warranties/cities/', 'Backend\PurchaseController@get_by_states')->name('warranty.cities.states');
        Route::get('/warranties/postcode/', 'Backend\PurchaseController@get_by_cities')->name('warranty.postcode.cities');
        Route::get('/warranties/shops/', 'Backend\PurchaseController@get_by_shops')->name('warranty.sale.shops');
        
        Route::get('/warranties/{id}/edit/','Backend\PurchaseController@edit');
        Route::get('/warranties/{id}/delete/', 'Backend\PurchaseController@destroy')->name('warranty.delete');
        Route::get('/warranties/{id}/test/','Backend\PurchaseController@emailtest');
        
        Route::get('/warranties/autocomplete', 'Backend\PurchaseController@autocomplete')->name('warranty.autocomplete');
        Route::post('/warranties/re-upload-image',['as'=>'warranty.image.re.upload','uses'=>'Backend\PurchaseController@reuploadImages']);
        Route::post('/warranties/upload-image-media','Backend\PurchaseController@storeMedia')->name('warranty.store.media');
        Route::post('/warranties/remove-image-media','Backend\PurchaseController@deleteMedia')->name('warranty.remove.media');
        Route::get('/warranties/checkemail', 'Backend\PurchaseController@checkemail')->name('warranty.check.email');
        
        
        Route::resource('/team','Backend\TeamPurchaseController');
        
        //Users
        Route::resource('/users','Backend\UsersController');
        
        // Sales PIC
        Route::resource('/sales','Backend\SalesManagerController');
        Route::get('/sales/{id}/edit/','Backend\SalesManagerController@edit');
        Route::get('/sales/{id}/delete/', 'Backend\SalesManagerController@destroy')->name('sales.delete');
        
        // Regional Manager
        Route::get('/managers/my-sales-team/','Backend\SalesManagerController@mysales')->name('my.sales.team');
        Route::resource('/managers','Backend\RegionalSalesManagerController');
        Route::get('/managers/{id}/edit/','Backend\RegionalSalesManagerController@edit');
        Route::get('/managers/{id}/delete/', 'Backend\RegionalSalesManagerController@destroy')->name('managers.delete');
        
        

        Route::get('/change-password', 'Backend\DashboardController@changePassword')->name('admin.change.password.form'); 

app/Models/GlobalEmailTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;

class GlobalEmailTemplate extends Model
{
    public static function boot()
     {
        parent::boot();
        static::creating(function($model)
        {
            $user = Auth()->guard('admin')->user();
            $model->created_by = $user->id;
            $model->updated_by = $user->id;
        });
        static::updating(function($model)
        {
            $user = Auth()->guard('admin')->user();
            $model->updated_by = $user->id;
        });       
    }
    protected $fillable = [
        'name', 'code', 'subject', 'template', 'status'
    ];
    
    public function parse($data)
    {
        $parsed = preg_replace_callback('/{{(.*?)}}/', function ($matches) use ($data) {
            list($shortCode, $index) = $matches;

            if (isset($data[$index])) {
                return $data[$index];
            } else {
                //throw new Exception("Shortcode {$shortCode} not found in template id {$this->id}", 1);
            }

        }, $this->template);

        return $parsed;
    }
    
    public function parsesubject($data)
    {
        $parsed = preg_replace_callback('/{{(.*?)}}/', function ($matches) use ($data) {
            list($shortCode, $index) = $matches;

            if (isset($data[$index])) {
                return $data[$index];
            } else {
                //throw new Exception("Shortcode {$shortCode} not found in template id {$this->id}", 1);
            }

        }, $this->subject);

        return $parsed;
    }
}

app/Http/Controllers/Backend/GlobalEmailTemplatesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\GlobalEmailTemplate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Admin;

class GlobalEmailTemplatesController extends Controller
{
    public $user;


    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user = Auth::guard('admin')->user();
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (is_null($this->user) || !$this->user->can('email.view')) {
            abort(403, 'Sorry !! You are Unauthorized to view any role !');
        }
        $breadcrumbs = [['link' => "/", 'name' => "Home"], ['name' => "All Email Template"]];
        $emailtemplates = GlobalEmailTemplate::latest()->get();
        return view('admin.global-email-templates.index', ['breadcrumbs' => $breadcrumbs], compact('emailtemplates'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        if (is_null($this->user) || !$this->user->can('email.create')) {
            abort(403, 'Sorry !! You are Unauthorized to view any role !');
        }
        $breadcrumbs = [['link' => "/", 'name' => "Home"], ['link' => route('global-email-templates.index'), 'name' => "All Email Template"], ['name' => "Create"]];
        return view('admin.global-email-templates.create', ['breadcrumbs' => $breadcrumbs]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->all();
        $this->validate($request,[
            'name'=>'string|required',
            'code'=>'string|nullable',
            'subject'=>'string|required',
            'template'=>'string|nullable',
            'status'=>'required|in:yes,no'
        ]);

        $data=$request->all();


        // return $data;

        $status=GlobalEmailTemplate::create($data);
        if($status){
            //request()->session()->flash('success','Post Successfully added');
            $msg = 'Email Template Successfully added';
        }
        else{
            //request()->session()->flash('error','Please try again!!');
            $msg = 'Please try again!!';
        }
        return redirect()->route('global-email-templates.index')->with('success', $msg);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\GlobalEmailTemplate  $globalEmailTemplate
     * @return \Illuminate\Http\Response
     */
    public function show(GlobalEmailTemplate $globalEmailTemplate)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\GlobalEmailTemplate  $globalEmailTemplate
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (is_null($this->user) || !$this->user->can('email.edit')) {
            abort(403, 'Sorry !! You are Unauthorized to view any role !');
        }
        $emailtemplate=GlobalEmailTemplate::findOrFail($id);
        $breadcrumbs = [['link' => "/", 'name' => "Home"], ['link' => route('global-email-templates.index'), 'name' => "All Email Template"], ['name' => "Edit"]];
        return view('admin.global-email-templates.edit', ['breadcrumbs' => $breadcrumbs])->with('emailtemplate',$emailtemplate);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\GlobalEmailTemplate  $globalEmailTemplate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post=GlobalEmailTemplate::findOrFail($id);
        $this->validate($request,[
            'name'=>'string|required',
            'subject'=>'string|required',
            'template'=>'string|nullable',
            'status'=>'required|in:yes,no'
        ]);

        $data=$request->all();


        // return $data;

        $status=$post->fill($data)->save();
        if($status){
            //request()->session()->flash('success','Post Successfully added');
            $msg = 'Email Template Successfully update';
        }
        else{
            //request()->session()->flash('error','Please try again!!');
            $msg = 'Please try again!!';
        }
        return redirect()->route('global-email-templates.index')->with('success', $msg);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\GlobalEmailTemplate  $globalEmailTemplate
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (is_null($this->user) || !$this->user->can('email.delete')) {
            abort(403, 'Sorry !! You are Unauthorized to view any role !');
        }
        GlobalEmailTemplate::destroy($id);
        return redirect()->route('global-email-templates.index')->with('success', 'Delete successfully!');
    }
}

resources/views/admin/global-email-templates/create.blade.php
@extends('admin.layouts.app')

@section('title')
Email Template - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->
    <link href="{{ asset('themes/dashforge/lib/quill/quill.core.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/quill/quill.snow.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/quill/quill.bubble.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-12"><h4 class="mg-b-0">Create</h4></div>
  
</div>


<div class="row mg-t-20 mg-b-20">
    <div class="col-sm-9">
        <form method="post" action="{{route('global-email-templates.store')}}" class="form" novalidate>
            {{csrf_field()}}
            <div class="form-body">
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="projectinput1">Code</label>
                            <input type="text" value="{{ Helper::getToken(6) }}" id="projectinput1" class="form-control" placeholder="Template Code" name="code" readonly="readonly">

                            @if ($errors->has('code'))
                            <span class="text-danger">{{ $errors->first('code') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="Name" class="required">Name</label>
                            <input type="text" value="{{old('name')}}" id="name" class="form-control" placeholder="Template Name" name="name" required>
                            @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="Subject" class="required">Subject</label>
                            <input type="text" value="{{old('subject')}}" id="subject" class="form-control" placeholder="Email Subject" name="subject" required>
                            @if ($errors->has('subject'))
                            <span class="text-danger">{{ $errors->first('subject') }}</span>
                            @endif
                        </div>
                    </div>
                </div>



                <div class="form-group">
                    <label for="projectinput8" class="required">Body</label>
                    <textarea id="template" rows="15" class="form-control ht-200" name="template" placeholder="Email Body"></textarea>
                    @if ($errors->has('template'))
                    <span class="text-danger">{{ $errors->first('template') }}</span>
                    @endif
                </div>

                <div class="form-group">
                    <label for="status" class="required">Status</label>
                    <select name="status" class="form-control">
                        <option selected>Pick Status</option>
                        <option value="yes">Yes</option>
                        <option value="no">No</option>
                    </select>
                    @if ($errors->has('status'))
                    <span class="text-danger">{{ $errors->first('status') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-actions">
                <a href="{{route('global-email-templates.index')}}" class="btn btn-warning mr-1"><i class="ft-x"></i> Cancel</a>

                <button type="submit" class="btn btn-primary">
                    <i class="la la-check-square-o"></i> Save
                </button>
            </div>
        </form>

    </div>
    <div class="col-sm-3">
        <?php
        //$path = storage_path() . "/json/shortcode.json"; // ie: /var/www/laravel/app/storage/json/filename.json
        $path = storage_path('app/public/json/shortcode.json');
        $shortcodes = json_decode(file_get_contents($path), true);
        //dd($shortcodes['shortcodes']);
        foreach ($shortcodes['shortcodes'] as $shortcode) {
            echo $shortcode;
        }
        ?>
    </div>
</div>




@endsection

@section('vendor-script')
     <!-- Start datatable js -->
<script src="//cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
@endsection

@section('page-script')
    <script type="text/javascript">

    CKEDITOR.replace('template', {
        allowedContent : true,
        filebrowserBrowseUrl : '/admin/elfinder/ckeditor',
        filebrowserImageBrowseUrl : '/admin/elfinder/ckeditor',
        //uiColor : '#9AB8F3',
        height : 600
    });
</script>
@endsection

resources/views/admin/global-email-templates/edit.blade.php
@extends('admin.layouts.app')

@section('title')
Email Template - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->    
@endsection

@section('content')
<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-12"><h4 class="mg-b-0">Edit - {{$emailtemplate->name}}</h4></div>
  
</div>


<div class="row mg-t-20 mg-b-20">
    <div class="col-sm-9">

        <form method="post" action="{{route('global-email-templates.update',$emailtemplate->id)}}" class="form" novalidate>
            {{ method_field('PUT') }}
            {{ csrf_field() }} 
            <div class="form-body">
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="code">Code</label>
                            <input type="text" value="{{$emailtemplate->code}}" id="code" class="form-control" placeholder="Template Code" readonly="readonly">
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="name" class="required">Name</label>
                            <input type="text" value="{{$emailtemplate->name}}" id="name" class="form-control" placeholder="Template Name" name="name" required>
                            @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="subject" class="required">Subject</label>
                            <input type="text" value="{{$emailtemplate->subject}}" id="subject" class="form-control" placeholder="Email Subject" name="subject" required>
                            @if ($errors->has('subject'))
                            <span class="text-danger">{{ $errors->first('subject') }}</span>
                            @endif
                        </div>
                    </div>
                </div>



                <div class="form-group">
                    <label for="projectinput8" class="required">Body</label>
                    <textarea id="classic-editor" rows="10" cols="80" class="form-control" name="template" placeholder="Email Body">{{$emailtemplate->template}}</textarea>
                    @if ($errors->has('code'))
                            <span class="text-danger">{{ $errors->first('code') }}</span>
                            @endif
                </div>

                <div class="form-group">
                    <label for="status" class="required">Status</label>
                    <select name="status" class="form-control">
                        <option selected>Pick Status</option>
                        <option value="yes" <?= $emailtemplate->status === 'yes' ? 'selected' : '' ?>>Yes</option>
                        <option value="no" <?= $emailtemplate->status === 'no' ? 'selected' : '' ?>>No</option>
                    </select>
                    @if ($errors->has('status'))
                            <span class="text-danger">{{ $errors->first('status') }}</span>
                            @endif
                </div>
            </div>

            <div class="form-actions">
                <a href="{{route('global-email-templates.index')}}" class="btn btn-warning mr-1"><i class="ft-x"></i> Cancel</a>
                <button type="submit" class="btn btn-primary">
                    <i class="la la-check-square-o"></i> Save
                </button>
            </div>
        </form>

    </div>
    <div class="col-sm-3">
        <?php
        //$path = storage_path() . "/json/shortcode.json"; // ie: /var/www/laravel/app/storage/json/filename.json
        $path = storage_path('app/public/json/shortcode.json');
        $shortcodes = json_decode(file_get_contents($path), true);
        //dd($shortcodes['shortcodes']);
        foreach ($shortcodes['shortcodes'] as $shortcode) {
            echo $shortcode;
        }
        ?>
    </div>
</div>
@endsection

@section('vendor-script')
  <!-- vendor files -->
    <script src="{{ asset('themes/modern-admin/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js') }}"></script>
    <script src="//cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
@endsection
@section('page-script')

  <!-- Page js files -->
  @include('panels/messages')
  <script src="{{ asset('themes/modern-admin/app-assets/js/scripts/forms/validation/form-validation.js') }}"></script>
  <script type="text/javascript">
    CKEDITOR.replace('template', {
        //fullPage : true,
        allowedContent : true,
        filebrowserBrowseUrl : '/admin/elfinder/ckeditor',
        filebrowserImageBrowseUrl : '/admin/elfinder/ckeditor',
        //uiColor : '#9AB8F3',
        height : 600
    });
</script>
@endsection

resources/views/admin/global-email-templates/index.blade.php
@extends('admin.layouts.app')

@section('title')
Email Template - Admin Panel
@endsection

@section('vendor-style')
    <!-- Start datatable css -->
    
    <link href="{{ asset('themes/dashforge/lib/datatables.net-dt/css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ asset('themes/dashforge/lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('content')


<div class="row mg-t-20 mg-b-20">
  <div class="col-sm-8"><h4 class="mg-b-0">Email Template</h4></div>
  <div class="col-sm-4 text-right">
      <a class="btn btn-primary mr-1 mb-1 btn-sm" href="{{ route('global-email-templates.create') }}">Create New</a>
  </div>
</div>

<div class="df-example demo-table">
    <table id="example1" class="table">
        <thead>
            <tr>
                <th width="5%">#</th>
                <th width="10%">Code</th>
                <th width="60%">Name</th>
                <th width="15%">Status</th>
                <th width="10%">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($emailtemplates as $emailtemplate)
            <tr id="category_id_{{ $emailtemplate->id }}">
                <td>{{ $loop->index+1 }}</td>
                <td>{{ $emailtemplate->code }}</td>
                <td>{{ $emailtemplate->name }}</td>
                <td>
                    @if($emailtemplate->status=='yes')
                    <span class="badge badge-success">{{ucwords($emailtemplate->status)}}</span>
                    @else
                    <span class="badge badge-danger">{{ucwords($emailtemplate->status)}}</span>
                    @endif
                </td>
                <td>
                    <a href="{{route('global-email-templates.edit',$emailtemplate->id)}}" id="edit-email-templates" class="btn btn-xs btn-info" data-toggle="tooltip" data-placement="bottom" title="Edit"><i data-feather="edit"></i></a>
                    <a href="{{route('global-email-templates.delete',[$emailtemplate->id])}}" class="btn btn-xs btn-danger" data-toggle="tooltip" data-placement="bottom" title="Delete" onclick="return confirm('Are you sure to delete this item?')"><i data-feather="trash"></i></a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
</div>

@endsection

@section('vendor-script')
     <!-- Start datatable js -->
    <script src="{{ asset('themes/dashforge/lib/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-dt/js/dataTables.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js') }}"></script>
    <script src="{{ asset('themes/dashforge/lib/select2/js/select2.min.js') }}"></script>
@endsection

@section('page-script')
    <script>
      $(function(){
        'use strict'

        $('#example1').DataTable({
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          }
        });
        $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
      });
    </script>
@endsection